### ISSUE TITLE
Store frame titles

### ISSUE THREAD

**Issue by edgar-vincent** [alphapapa/burly.el#19]
Hello,

I think it would be useful if burly stored frame titles in its bookmarks, in order for frames to be identifiable by scripts. It would, for instance, allow users of tiling window managers such as Sway or i3 to restore frames in different workspaces automatically.

Thank you very much for your work!
EV

**Comment by alphapapa** [comment]
Hi Edgar,

I think this branch should do it.  Would you please test it and let me know if it works for you?

Thanks.
