### ISSUE TITLE
Symbol's value as variable is void: frame-width

### ISSUE THREAD

**Issue by diamond-lizard** [alphapapa/burly.el#2]
In a Bookmark Menu mode buffer, when I eval ```bookmark-bmenu-this-window``` while point is on a bookmark saved via ```burly-bookmark-windows```, I get an error:

```Symbol's value as variable is void: frame-width```

- [Here is a backtrace](https://github.com/alphapapa/burly.el/files/5427041/burly-backtrace.txt)
- [Here is my bookmarks file](https://github.com/alphapapa/burly.el/files/5427196/burly-bookmarks.txt)

I wonder if this issue might be caused by my having no frames in my emacs, since I compiled emacs using the ```--without-x``` option, as I use Emacs only in a terminal.

I'm on emacs 27.1 on Gentoo Linux, with the following compilation options:

```
 'configure --prefix=/usr --build=x86_64-pc-linux-gnu --host=x86_64-pc-linux-gnu --mandir=/usr/share/man --infodir=/usr/share/info --datadir=/usr/share --sysconfdir=/etc --localstatedir=/var/lib --disable-silent-rules --docdir=/usr/share/doc/emacs-27.1-r1 --htmldir=/usr/share/doc/emacs-27.1-r1/html --libdir=/usr/lib64 --program-suffix=-emacs-27 --includedir=/usr/include/emacs-27 --infodir=/usr/share/info/emacs-27 --localstatedir=/var --enable-locallisppath=/etc/emacs:/usr/share/emacs/site-lisp --without-compress-install --without-hesiod --without-pop --with-dumping=pdumper --with-file-notification=inotify --enable-acl --without-dbus --with-modules --without-gameuser --with-libgmp --without-gpm --with-json --without-kerberos --without-kerberos5 --without-lcms2 --with-xml2 --without-mailutils --without-selinux --with-gnutls --without-libsystemd --with-threads --without-wide-int --with-zlib --with-sound=alsa --without-x --without-ns 'CFLAGS=-O2 -march=native -pipe' CPPFLAGS= 'LDFLAGS=-Wl,-O1 -Wl,--as-needed''
```

**Comment by alastairdb** [comment]
See my rejected pull request - https://github.com/alphapapa/burly.el/pull/1 

You can fix this by applying my commit or by carefully byte-compiling files by hand

**Comment by alphapapa** [comment]
@diamond-lizard You didn't say how you installed this package.  Anyway, you simply need to install the current version of the `map` library from ELPA; and if you byte-compiled Burly, you'll then need to do that again.

If you follow the recommended installation method using Quelpa, that handles it automatically.
