### ISSUE TITLE
burly-open-bookmark completion shows no entries after startup

### ISSUE THREAD

**Issue by minad** [alphapapa/burly.el#21]
Hi,

I like the idea of reusing builtin functionality for the purpose of storing window/frame configuration! I've one small issue though - After starting Emacs, `M-x burly-open-bookmark` shows no entries, since the bookmark file is somehow not yet loaded. After `M-x bookmark-jump` the file is loaded and then burly is populated too, when doing `M-x burly-open-bookmark` again.

Independently of the issue, I wonder if it is necessary to do the URL encoding? It seems to me that bookmarks can be simple alists? Generally I would prefer to use the native elisp format instead of the less readable url encoding. Or maybe there is a technical reason to use the url format? Is it the idea that urls are better for external sharing? Does burly also hook into some internal emacs url mechanism for opening urls? Your readme states that you also provide commands working with the URL strings, with the added qualification that most users probably won't use these.

**Comment by alphapapa** [comment]
Thanks, that will be a simple bug to fix.  I assumed that `bookmark-allist` was loaded automatically, but apparently not.

URLs are an implementation detail at the moment.  For more discussion, please see https://github.com/alphapapa/burly.el/issues/7

**Comment by minad** [comment]
@alphapapa Thank you for the answer, I will read through #7 and maybe comment there!

**Comment by ssl19** [comment]
According to [bookmark-view.el](https://github.com/minad/bookmark-view/blob/59078eaa37ec168c37d52798c9f1020741271a64/bookmark-view.el#L141), I've found out a workaround :
`(advice-add 'burly-bookmark-names :before (lambda () (bookmark-maybe-load-default-file)))`

I'm not very familiar with Emacs and Elisp, so I don't know if this has a disadvantage
