### ISSUE TITLE
Feature: Update bookmarks

### ISSUE THREAD

**Issue by Kungsgeten** [alphapapa/burly.el#25]
Hi! I'm enjoying Burly quite a bit, thank you for the package!

A feature request is making it easier to update an already existing bookmark. At the moment (I think) you have to `M-x burly-bookmark-windows` and then type letter by letter the same name as you've already saved. Perhaps instead of `read-string` we could use `completing-read` and let us choose among already defined Burly window/frame bookmarks?

**Comment by alphapapa** [comment]
Hi,

I'm glad it's been useful to you.

That sounds like a good idea, yes, as long as it doesn't interfere with typing a name that doesn't already exist as a bookmark.

Would you be interested in submitting a patch?

**Comment by Kungsgeten** [comment]
Sure, I'll have a go at it!

**Comment by alphapapa** [comment]
Thanks.
