### ISSUE TITLE
burly-open-bookmark fails when called immediately after delete-other-windows

### ISSUE THREAD

**Issue by dkmestre95** [alphapapa/burly.el#33]
Running the function `burly-open-bookmark` immediately after calling `delete-other-windows` fails to open the selected layout. Instead, what happens is one window is opened horizontally (as with `split-window-below`), and I'm presented with the following error: 

> Wrong type argument: window-live-p, nil

To replicate this, do the following:

1. Open any number of windows.
2. Run `delete-other-windows`
3. Run `burly-open-bookmark`
4. Select a bookmark to open (whether it be newly created or not)

**Comment by dkmestre95** [comment]
Also for clarity, running `burly-open-bookmark` immediately after encountering this error will open the layout as intended. Hope this helps.

**Comment by alphapapa** [comment]
Can you reproduce this problem in a clean Emacs config?  If so, please report the versions of Emacs and of this package.
