### ISSUE TITLE
Saving non-narrowed org buffers

### ISSUE THREAD

**Issue by tpeacock19** [alphapapa/burly.el#38]
Since this commit cd1715d318fe831612bbc880b498c483ee958665 I have been unable to save org buffers that do not have a heading in the first line. I get thrown an error `Before first headline at position 1 in buffer wiki.org`. 

I believe this is an error in `burly--org-mode-buffer-url`, specifically the top-olp section:

```elisp
(when (org-heading-components)
                (org-with-wide-buffer
                 (nreverse (cl-loop collect (substring-no-properties (nth 4 (org-heading-components)))
                                    while (org-up-heading-safe)))))
```

If the buffer is not narrowed `org-heading-components` will result in a user-error. This can be mitigated with the following:

```diff
diff --git a/burly.el b/burly.el
index a18555b..4ee17a5 100644
--- a/burly.el
+++ b/burly.el
@@ -439,7 +439,7 @@ URLOBJ should be a URL object as returned by
               (goto-char (point-min))
               ;; `org-get-outline-path' replaces links in headings with their
               ;; descriptions, which prevents using them in regexp searches.
-              (when (org-heading-components)
+              (when (and (buffer-narrowed-p) (org-heading-components))
                 (org-with-wide-buffer
                  (nreverse (cl-loop collect (substring-no-properties (nth 4 (org-heading-components)))
                                     while (org-up-heading-safe)))))))
```

**Comment by alphapapa** [comment]
Thanks; I was afraid that I might have caused a bug like this, but I was hoping not.  This "before first heading" issue happens *so often* in Org-related packages...

I'm not sure that the change you propose will fix it correctly.  In non-narrowed Org buffers, the current heading should still be selected when point is in an entry rather than before the first one.  I think that, rather than testing whether the buffer is narrowed, we should probaly test `org-before-first-heading-p`.

**Comment by tpeacock19** [comment]
> I'm not sure that the change you propose will fix it correctly. In non-narrowed Org buffers, the current heading should still be selected when point is in an entry rather than before the first one.

Doesn't this case get handled by the `point-olp`? I'm pretty sure this captures the current heading at point.

**Comment by hrehfeld** [comment]
I can confirm the bug as well as the proposed fix.

**Comment by alphapapa** [comment]
Thanks.  Would one or both of you mind testing this branch?  It tests narrowing earlier in the form.  https://github.com/alphapapa/burly.el/commit/9b5b480f1f378e7d8873bfaa2c4fa175ed687ef0

**Comment by tpeacock19** [comment]
I can confirm that this works saving non-narrowed and narrowed buffers.

**Comment by alphapapa** [comment]
Thanks!

**Comment by hrehfeld** [comment]
Did you test this on an empty buffer? Otherwise we might still need something like `(when (and (org-at-heading-p) (org-heading-components))`.
