### ISSUE TITLE
indirect buffers not restored

### ISSUE THREAD

**Issue by ParetoOptimalDev** [alphapapa/burly.el#50]
Narrowing org bookmarks work great!

However I noticed that indirect buffers don't, so I guess this would be a feature request.

#49 doesn't apply here because I tested this without deleting any buffers or closing emacs.

**Comment by alphapapa** [comment]
You can see in the implementation that indirect buffers are specifically supported: https://github.com/alphapapa/burly.el/blob/c94fe0a355859fe6ddfa34cf7d362dca896f38a1/burly.el#L458  And AFAIK, they work fine (they do for me).  If they don't work for you, you'll need to be more specific about the software and versions you're using, and please try to reproduce in a clean Emacs config.

**Comment by ParetoOptimalDev** [comment]
I believe I used a clean config with 27. I'll check and update this issue when back at pc. Sorry, must have been in a hurry.
