### ISSUE TITLE
Make burly-tabs-mode magit branch aware

### ISSUE THREAD

**Issue by ParetoOptimalDev** [alphapapa/burly.el#52]
If I call burly-bookmark-windows and magit has checked out a certain branch or worktree I'd like it to restore that.

I'm open to the argument burly should only restore worktrees so bookmarks never clobber, but I bet branches would probably be fine.

Maybe this is more appropriate as a seperate package? If not, I'd be happy to try to implement this and send a PR.

**Comment by alphapapa** [comment]
That's an interesting idea, but it's well out of Burly's scope.  Burly restores windows and frames.

**Comment by alphapapa** [comment]
More specifically, this sounds like a matter of bookmarking magit-status buffers to certain branches, which is also outside of Burly's scope.  You could accomplish something like this already by checking out a branch into a worktree and bookmarking that worktree's status buffer.
