### ISSUE TITLE
Burly fails at opening/recreating orgit buffer

### ISSUE THREAD

**Issue by TauPan** [alphapapa/burly.el#57]
(Again new burly user here, forgive me is that is known/documented already.)

This is probably a very specific use-case failing for me.

I have a link `orgit-topic:Z2l0LmRmbi1jZXJ0LmRlOjUxOmlzc3VlMTA2MQ==` in an org-mode buffer which opens a forge topic (an issue). 

~~~
Burly was unable to get a buffer named: *forge: pet/SIS/sis 
URL: emacs+burly+name://?*forge: pet/SIS/sis #1061*
Please report this error to the developer
~~~

`ivy-push-view` is able to refer it, but also by name only: `(("{} *forge: pet/SIS/sis #1061* Cert.org" #<window-configuration>))`

I don't know how to get the information that would be needed from orgit to recreate the buffer.

Note that this fails even if the buffer exists.

**Comment by alphapapa** [comment]
Hi Friedrich,

Yes, that means that `orgit` doesn't provide Emacs bookmarks support, which is used by Burly to recreate buffers.  So the solution is for the `orgit` package to gain a bookmark handler function and a bookmark make-record function.  It's usually very simple to implement; see, e.g. this in Ement.el: https://github.com/alphapapa/ement.el/blob/27929d80ff2d9ea01b3f5ca673a9190956d06ea9/ement-room.el#L987  IIRC Jonas Bernoulli is the `orgit` maintainer, so he could certainly handle that, if he has time.  But feel free to give it a try yourself.  :)

**Comment by TauPan** [comment]
See https://github.com/magit/forge/discussions/555 ... (I thin I was wrong about orgit being the relevant library here, it's a forge buffer, but magit has other buffers that orgit supports, so maybe the discussion is not in the right place either.) In any case this can be closed.
