### ISSUE TITLE
Feature Request: Add burly-open-bookmark command

### ISSUE THREAD

**Issue by rswgnu** [alphapapa/burly.el#6]
This would interactively filter bookmarks to just burly ones, showing the names without the 'Burly: ' prefix, or allow passing a bookmark string without the burly prefix, then would add the prefix and invoke bookmark-jump.  Nice and simple.

**Comment by alphapapa** [comment]
Hi Rob,

Yeah, that's not a bad idea.  I should probably move the bookmark name prefix into the prompt as well, so users aren't forced to use it.

Thanks.

**Comment by alphapapa** [comment]
Hi Rob,

I added a command like you suggested.  I also changed the `burly-bookmark-windows` command to not force a `Burly: ` prefix on the bookmark name, so I didn't make the new command accept a string argument (Burly bookmarks are found by filtering on the bookmarks' handler function).  If you need a way to get a list of Burly bookmarks, let me know and I can move that code into a function so you can call it.

Thanks.
