### ISSUE TITLE
Save/restore multiple frames

### ISSUE THREAD

**Issue by poulpoulsen** [alphapapa/burly.el#8]
Hello,
i just discovered, that burly could not restore more then one frame.
Is this a development status  or a bug?
I create three frames with C-x 5 2.
Then i saved the bookmark.
bookmark-jump restored only one frame with all windows.

Regards
Poul

**Comment by alphapapa** [comment]
Hi Poul,

As the documentation says, the `burly-bookmark-windows` command bookmarks "the current frame’s window configuration."  It may be possible to write another command to restore multiple frames.  I may look into that sometime.  In the meantime, you'll have to bookmark each frame separately.

**Comment by poulpoulsen** [comment]
Thank you.
I will handle this for multiple frames and hope that in the future, there will be an enhancement for saving all frames at once.
.

**Comment by rswgnu** [comment]
See: https://github.com/alphapapa/burly.el/issues/7#issuecomment-716920511

**Comment by alphapapa** [comment]
@poulpoulsen @rswgnu Implemented with https://github.com/alphapapa/burly.el/commit/be43270fccb83ad27954544974a38eb2c8360f72.  Lightly tested, but it seems to work.  Please let me know how it works for you.

**Comment by alphapapa** [comment]
BTW, what do you think about removing the `burly-bookmark-windows` command and moving its functionality into `burly-bookmark-frame`?  It would bookmark the current frame, and with a prefix argument it would bookmark all frames.  I feel like that might be clearer to users.

**Comment by rswgnu** [comment]
I would have two commands:  burly-bookmark-frameset for multiple frames and burly-bookmark-wconfig (to use the Emacs term) or burly-bookmark-frame if you prefer.  It would be okay for a prefix arg to the wconfig cmd to invoke the frameset command but I think you want the functions do be separate when programming to distinguish the types if objects they store

**Comment by alphapapa** [comment]
That's a good idea.  Thanks.
